# Generated by Django 5.1.2 on 2024-11-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctor_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
