# Generated by Django 5.1.2 on 2024-11-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empleado_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/', verbose_name='Foto del Medicamento'),
        ),
    ]
