# Generated by Django 5.1.2 on 2024-11-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tipocategoria_categoria_examen_and_more'),
        ('core', '0009_medicamento_foto'),
    ]

    operations = [
    ]
