# Generated by Django 5.1.2 on 2024-11-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20241114_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
    ]
